services:
    wc-provider:
        restart: unless-stopped
        container_name: wc_provider
        networks:
            - wc-network
        build:
            context: ..
            dockerfile: docker/Dockerfile
            target: development-artisan
        ports:
            - "8000:8000"
        volumes:
            - ../:/var/www/html
        env_file:
            - ../.env
        depends_on:
            wc-postgres:
                condition: service_healthy
            wc-redis:
                condition: service_healthy
        healthcheck:
            test: [ "CMD-SHELL", "curl -s -f -X GET http://localhost:8000/up | grep -q 'Application up' || exit 1" ]
            interval: 30m
            timeout: 5s
            retries: 3
            start_period: 30s

    wc-queue:
        restart: unless-stopped
        container_name: wc_queue
        networks:
            - wc-network
        build:
            context: ..
            dockerfile: docker/Dockerfile
            target: development-queue
        volumes:
            - ../:/var/www/html
        env_file:
            - ../.env
        depends_on:
            wc-provider:
                condition: service_healthy
        healthcheck:
            test: [ "CMD-SHELL", "ps aux | grep '[q]ueue:listen' || exit 1" ]
            interval: 30m
            timeout: 5s
            retries: 3
            start_period: 30s

    wc-reverb:
        restart: unless-stopped
        container_name: wc_reverb
        networks:
            - wc-network
        build:
            context: ..
            dockerfile: docker/Dockerfile
            target: development-reverb
        ports:
            - "8080:8080"
        volumes:
            - ../:/var/www/html
        env_file:
            - ../.env
        depends_on:
            wc-provider:
                condition: service_healthy
        healthcheck:
            test: [ "CMD-SHELL", "ps aux | grep '[r]everb:start' || exit 1" ]
            interval: 30s
            timeout: 5s
            retries: 3
            start_period: 30s

    wc-postgres:
        image: postgres:latest
        restart: always
        container_name: wc_postgres
        networks:
            - wc-network
        environment:
            POSTGRES_USER: wc_postgres
            POSTGRES_PASSWORD: wc_postgres
            POSTGRES_DB: wc_postgres
        ports:
            - "5432:5432"
        volumes:
            - wc-postgres-data:/var/lib/postgresql/data
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U wc_postgres" ]
            interval: 30m
            timeout: 5s
            retries: 5
            start_period: 10s

    wc-redis:
        image: redis:latest
        restart: always
        container_name: wc_redis
        command: bash -c "echo 1 > /proc/sys/vm/overcommit_memory && redis-server"
        privileged: true
        networks:
            - wc-network
        ports:
            - "6379:6379"
        volumes:
            - wc-redis-data:/data
        healthcheck:
            test: [ "CMD", "redis-cli", "ping" ]
            interval: 30m
            timeout: 5s
            retries: 5
            start_period: 10s

networks:
    wc-network:
        driver: bridge

volumes:
    wc-postgres-data:
    wc-redis-data:
