services:
    laxtive-provider:
        restart: unless-stopped
        container_name: laxtive_provider
        networks:
            - laxtive-network
        build:
            context: ..
            dockerfile: docker/Dockerfile
            target: development-artisan
        ports:
            - "8000:8000"
        volumes:
            - ../:/var/www/html
        env_file:
            - ../.env
        depends_on:
            laxtive-postgres:
                condition: service_healthy
            laxtive-redis:
                condition: service_healthy
        healthcheck:
            test: [ "CMD-SHELL", "curl -s -f -X GET http://localhost:8000/up | grep -q 'Application up' || exit 1" ]
            interval: 30m
            timeout: 5s
            retries: 3
            start_period: 30s

    laxtive-queue:
        restart: unless-stopped
        container_name: laxtive_queue
        networks:
            - laxtive-network
        build:
            context: ..
            dockerfile: docker/Dockerfile
            target: development-queue
        volumes:
            - ../:/var/www/html
        env_file:
            - ../.env
        depends_on:
            laxtive-provider:
                condition: service_healthy
        healthcheck:
            test: [ "CMD-SHELL", "ps aux | grep '[q]ueue:listen' || exit 1" ]
            interval: 30m
            timeout: 5s
            retries: 3
            start_period: 30s

    laxtive-reverb:
        restart: unless-stopped
        container_name: laxtive_reverb
        networks:
            - laxtive-network
        build:
            context: ..
            dockerfile: docker/Dockerfile
            target: development-reverb
        ports:
            - "8080:8080"
        volumes:
            - ../:/var/www/html
        env_file:
            - ../.env
        depends_on:
            laxtive-provider:
                condition: service_healthy
        healthcheck:
            test: [ "CMD-SHELL", "ps aux | grep '[r]everb:start' || exit 1" ]
            interval: 30s
            timeout: 5s
            retries: 3
            start_period: 30s

    laxtive-postgres:
        image: postgres:latest
        restart: always
        container_name: laxtive_postgres
        networks:
            - laxtive-network
        environment:
            POSTGRES_USER: laxtive_postgres
            POSTGRES_PASSWORD: laxtive_postgres
            POSTGRES_DB: laxtive_postgres
        ports:
            - "5432:5432"
        volumes:
            - laxtive-postgres-data:/var/lib/postgresql/data
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U laxtive_postgres" ]
            interval: 30m
            timeout: 5s
            retries: 5
            start_period: 10s

    laxtive-redis:
        image: redis:latest
        restart: always
        container_name: laxtive_redis
        command: bash -c "echo 1 > /proc/sys/vm/overcommit_memory && redis-server"
        privileged: true
        networks:
            - laxtive-network
        ports:
            - "6379:6379"
        volumes:
            - laxtive-redis-data:/data
        healthcheck:
            test: [ "CMD", "redis-cli", "ping" ]
            interval: 30m
            timeout: 5s
            retries: 5
            start_period: 10s

networks:
    laxtive-network:
        driver: bridge

volumes:
    laxtive-postgres-data:
    laxtive-redis-data:
